[project]
name = "website-yuchen-xue"
version = "0.1.0"
description = "My personal website based on Jinja2 and Toml"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
]
